version: "3.7"

services:
  backend-db:
    image: postgres:15.5-bookworm
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/01-init-api-db.sh
    env_file:
      - ./.env.${NODE_ENV:-local}