#!/bin/bash

set -e

# Set amal database and semaphore database and grant provileges to postgres user
psql -v ON_ERROR_STOP=1 -U ${POSTGRES_USER} <<-EOSQL
    ALTER USER postgres WITH PASSWORD '${POSTGRES_PASSWORD}';
    CREATE DATABASE "${DB_NAME}";
    GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME}" TO ${POSTGRES_USER};

    \connect ${DB_NAME};
    CREATE SCHEMA IF NOT EXISTS public;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    DROP TABLE IF EXISTS STUDENTS;
    CREATE TABLE IF NOT EXISTS STUDENTS (ID SERIAL PRIMARY KEY , FIRST_NAME TEXT NOT NULL, LAST_NAME TEXT, CITY TEXT NOT NULL, PHONE TEXT NOT NULL , EMAIL TEXT NOT NULL );
EOSQL